directories:
  train_dir: "train_dir"
  val_dir: "val_dir"
  checkpoint_dir: "checkpoint_dir"
  writer: "writer_directory"
  checkpoint_name: "checkpoint_name"

HyperParameters:
  batch_size: 32
  num_classes: 3
  num_epochs: 100
  learning_rate: 5e-5
  device: "cuda"
  patience: 10
  warmup_epochs: 10
  accuracy_weights: 0.7
  loss_weights: 0.3
  alpha: 0.1 # expoenetiallly moving averages 
  delta: 1e-2   # threshold change in score for pateince
  weight_decay: 5e-3
  label_smoothening: 0.1
  train_batch_size: 64
  val_batch_size: 32
